version: '3'

services:
  postgres:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  mongodb:
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2023!
      MONGO_INITDB_DATABASE: pontuaweb
    volumes:
      - mongodb-data:/data/db
    ports:
      - '27017:27017'

volumes:
  postgres-data:
    driver: local
  mongodb-data:
    driver: local
